name: no_ring_morse
description: "Morse Rington Generator."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  ffmpeg_kit_flutter: ^6.0.3
  flutter:
    sdk: flutter
  just_audio: ^0.9.39
  path_provider: ^2.1.3
  share_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  